import Footer from '@/components/Footer'
import './globals.css'
import { Inter } from 'next/font/google'
import Navbar from '@/components/Navbar'
import { Providers } from './globalredux/provider'
import HiddenComp from '@/components/HiddenComp'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Shop Envy',
  description: 'Generated by create next app',
  icons: {
    icon: '/icon.png',
  },
}

export default function RootLayout(props) {

  if(!process.env.NEXT_PUBLIC_WEBSITE){
    return null;
  };

  
  return (
    <html lang="en">
      <body className={inter.className}>

<Providers>

        {props.children}

<HiddenComp/>

        </Providers>

{/* <Footer/> */}

        
        
        </body>
    </html>
  )
}
