import Footer from '@/components/Footer'
import './globals.css'
import { Inter } from 'next/font/google'
import Navbar from '@/components/Navbar'
import { Providers } from './globalredux/provider'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout(props) {
  return (
    <html lang="en">
      <body className={inter.className}>

<Providers>

        {props.children}
        </Providers>

{/* <Footer/> */}

        
        
        </body>
    </html>
  )
}
